'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class slip_keputusan_sejarah1251
    
    '''<summary>
    '''slip_keputusan_sejarah12511 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slip_keputusan_sejarah12511 As Global.kpmkv.slip_keputusan_sejarah12511
End Class
